# General Purpose Agent Configuration
# Fallback agent for queries that don't match specialized agents or when specialists are unavailable

agent_id: "general-support"
version: "1.0.0"
status: "active"
last_updated: "2025-01-15T10:30:00Z"

# Agent Metadata
metadata:
  name: "General Support Assistant"
  description: "General purpose assistant for miscellaneous inquiries and fallback support"
  priority_level: 4  # Lower priority fallback agent (1-5 scale)
  category: "general_services"
  tags: ["general", "fallback", "miscellaneous", "backup"]

# Vector Database Configuration
vector_config:
  qdrant_collection: "general_support_v1"
  vector_size: 1536  # OpenAI ada-002 embedding dimensions
  distance_metric: "cosine"
  
  # Performance optimization settings (less aggressive than specialized agents)
  faiss_promotion_threshold: 200  # Higher threshold since less specialized
  redis_cache_ttl: 900  # 15 minutes - longer TTL for general info
  auto_optimize_schedule: "0 4 * * *"  # Daily optimization at 4 AM
  
  # General caching strategy
  general_info_cache_ttl: 1800     # 30 minutes for general information
  common_questions_cache_ttl: 3600  # 1 hour for FAQ-type content
  routing_decisions_cache_ttl: 600  # 10 minutes for routing decisions

# Knowledge Base Sources
knowledge_sources:
  - type: "documents"
    path: "kb/general/"
    categories:
      - "company_information"
      - "general_policies"
      - "frequently_asked_questions"
      - "service_overview"
      - "contact_information"
      - "business_hours"
      - "general_procedures"
    auto_update: true
    update_schedule: "0 */12 * * *"  # Every 12 hours
    
  - type: "api"
    name: "company_info_api"
    endpoint: "https://api.company.internal/general-info"
    auth_type: "api_key"
    auth_key_env: "COMPANY_API_KEY"
    refresh_interval: 7200  # 2 hours
    
  - type: "database"
    name: "general_policies"
    connection_string_env: "GENERAL_DB_CONNECTION"
    query: "SELECT * FROM general_policies WHERE active = true"
    refresh_interval: 3600  # 1 hour
    
  - type: "web_scraping"
    name: "company_website"
    base_url: "https://company.com"
    pages: ["/about", "/services", "/contact", "/faq"]
    refresh_interval: 86400  # Daily update
    respect_robots_txt: true

# Agent Specialization Configuration
specialization:
  system_prompt: |
    You are a helpful and knowledgeable general support assistant representing the company.
    
    CORE RESPONSIBILITIES:
    - Provide general information about company services and policies
    - Handle miscellaneous inquiries that don't fit specialized categories
    - Route customers to appropriate specialized agents when needed
    - Serve as backup when specialized agents are unavailable
    - Maintain friendly, professional customer service standards
    - Collect basic information for proper routing and follow-up
    
    ROUTING RESPONSIBILITIES:
    - Identify when customers need specialized help (roadside, billing, technical)
    - Explain what each specialized agent can help with
    - Collect preliminary information to help specialized agents
    - Provide estimated wait times and alternatives when specialists are busy
    
    COMMUNICATION STYLE:
    - Friendly, helpful, and professional
    - Patient with customers who aren't sure what they need
    - Clear about what you can and cannot help with
    - Proactive in offering to connect customers with specialists
    - Reassuring when transferring to other agents
    
    LIMITATIONS AWARENESS:
    - Be honest about your limitations compared to specialists
    - Don't attempt to handle complex technical, billing, or emergency issues
    - Always offer specialist referral for complex problems
    - Know when to escalate immediately (emergencies, urgent issues)
    
    INFORMATION GATHERING:
    - Ask clarifying questions to understand customer needs
    - Collect contact information for follow-up when appropriate
    - Document interaction summary for specialist handoff
    - Confirm customer understanding before transfers
    
    COMPANY REPRESENTATION:
    - Maintain positive company image and brand voice
    - Stay up-to-date on company policies and services
    - Provide accurate business hours and contact information
    - Handle complaints professionally and route to appropriate teams
    
    Always end interactions by asking: "Is there anything else I can help you with today, or would you like me to connect you with one of our specialists?"
    
  max_context_tokens: 2048
  response_style: "friendly_professional"
  temperature: 0.4  # Moderate temperature for natural but consistent responses
  max_response_tokens: 200  # Concise responses with referral options
  
  # General support patterns
  general_patterns:
    information_requests: ["what is", "tell me about", "explain", "how does", "information about"]
    company_inquiries: ["your company", "about you", "services", "what do you do", "business hours"]
    routing_needs: ["need help with", "having trouble", "want to speak to", "transfer me"]
    complaints: ["unhappy", "disappointed", "problem with service", "complaint", "dissatisfied"]

# Voice Configuration
voice_settings:
  tts_voice: "en-US-Neural2-H"  # Friendly, approachable voice
  speaking_rate: 1.0   # Normal speaking rate
  pitch: 1.0           # Slightly higher pitch for friendliness
  volume_gain_db: 0.5  # Standard volume
  personality: "friendly_helpful"
  
  # Customer service voice settings
  service_mode:
    speaking_rate: 0.95  # Slightly slower for clear communication
    pause_after_questions: 0.8  # Pause for customer to respond
    emphasis_on_options: true    # Emphasize available options
    warm_tone: true             # Maintain warm, welcoming tone

# Tool Integration Configuration
tools:
  - name: "route_to_specialist"
    type: "agent_routing"
    description: "Route customer to appropriate specialized agent"
    timeout: 3000
    parameters:
      required: ["agent_type", "customer_query", "priority_level"]
      optional: ["collected_info", "customer_preferences"]
    available_agents:
      - "roadside-assistance"
      - "billing-support" 
      - "technical-support"
    routing_logic: "confidence_based"
    
  - name: "check_agent_availability"
    type: "system_status"
    description: "Check availability and wait times for specialized agents"
    endpoint: "/api/agents/availability"
    timeout: 2000
    parameters:
      required: ["agent_type"]
      optional: ["priority_level"]
    cache_ttl: 30  # Cache for 30 seconds
    
  - name: "lookup_company_info"
    type: "knowledge_search"
    description: "Search company information and policies"
    timeout: 5000
    parameters:
      required: ["search_query", "category"]
      optional: ["detail_level"]
    search_categories:
      - "services"
      - "policies"
      - "contact_info"
      - "business_hours"
      - "locations"
      - "general_faq"
    
  - name: "create_general_ticket"
    type: "ticketing_system"
    description: "Create general support ticket for follow-up"
    provider: "zendesk"
    timeout: 8000
    parameters:
      required: ["customer_info", "inquiry_summary", "category"]
      optional: ["priority", "preferred_contact_method"]
    default_priority: "normal"
    auto_assign: true
    
  - name: "collect_customer_feedback"
    type: "feedback_system"
    description: "Collect customer feedback and satisfaction ratings"
    timeout: 5000
    parameters:
      required: ["interaction_id", "feedback_type"]
      optional: ["rating", "comments", "improvement_suggestions"]
    feedback_types:
      - "service_quality"
      - "agent_helpfulness"
      - "resolution_satisfaction"
      - "overall_experience"
    
  - name: "schedule_callback"
    type: "scheduling"
    description: "Schedule callback with appropriate team member"
    provider: "calendly"
    timeout: 5000
    parameters:
      required: ["customer_contact", "callback_reason", "preferred_time"]
      optional: ["specific_agent_type", "urgency_level"]
    callback_types:
      - "general_inquiry"
      - "complaint_resolution"
      - "service_consultation"
      - "follow_up_call"
    
  - name: "send_information_packet"
    type: "communication"
    description: "Send informational materials to customer"
    providers: ["email", "sms"]
    timeout: 5000
    parameters:
      required: ["customer_contact", "information_type"]
      optional: ["delivery_method", "follow_up_required"]
    information_types:
      - "service_brochure"
      - "pricing_information"
      - "contact_directory"
      - "policy_documents"
    
  - name: "escalate_complaint"
    type: "escalation"
    description: "Escalate customer complaints to management"
    timeout: 3000
    parameters:
      required: ["complaint_summary", "customer_info", "severity_level"]
      optional: ["attempted_resolution", "customer_sentiment"]
    escalation_levels:
      - "supervisor"
      - "department_manager"
      - "customer_relations"
      - "executive_team"

# Routing Configuration
routing:
  # General agent has broader, less specific keywords
  primary_keywords:
    - "general"
    - "information"
    - "help"
    - "question"
    - "about"
    - "company"
    - "service"
    - "policy"
    - "hours"
    - "contact"
    - "location"
    - "complaint"
    
  # Secondary keywords for fallback scenarios
  secondary_keywords:
    - "assistance"
    - "support"
    - "inquiry"
    - "tell me"
    - "explain"
    - "what is"
    - "how do"
    - "where is"
    - "when do"
    
  # Context patterns for general inquiries
  context_patterns:
    - "general question"
    - "not sure who to talk to"
    - "information about"
    - "want to know"
    - "can you tell me"
    - "need some help"
    - "have a question"
    
  # Lower confidence threshold since this is fallback
  confidence_threshold: 0.50  # Lower threshold for fallback agent
  fallback_routing: true      # This agent accepts fallback routing
  
  # Routing decision logic
  routing_decisions:
    emergency_keywords: "route_to_roadside"      # Route emergencies immediately
    billing_keywords: "route_to_billing"        # Route financial inquiries
    technical_keywords: "route_to_technical"    # Route technical issues
    general_keywords: "handle_locally"          # Handle general inquiries

# Performance Configuration
performance:
  target_response_time_ms: 1000  # Less aggressive target for general agent
  max_response_time_ms: 2000     # Higher acceptable latency
  
  # Caching strategy for general information
  cache_strategy:
    company_info: 3600         # Cache company info for 1 hour
    policies: 1800            # Cache policies for 30 min
    faq_responses: 7200       # Cache FAQ for 2 hours
    agent_availability: 30    # Cache availability for 30 seconds
    
  # Load balancing - handle overflow from specialists
  load_balancing:
    max_concurrent_sessions: 100  # Higher capacity for fallback
    queue_timeout_seconds: 120    # Longer timeout acceptable
    priority_queue: false         # No priority queue needed
    overflow_handling: true       # Accept overflow from specialists

# Monitoring and Analytics
monitoring:
  # Key performance indicators
  kpis:
    - "routing_accuracy_rate"
    - "customer_satisfaction_score"
    - "information_accuracy_rate"
    - "successful_referral_rate"
    - "fallback_usage_percentage"
    
  # Alerts specific to general agent
  alerts:
    - condition: "fallback_usage > 20%"
      severity: "warning"
      notification: ["slack", "email"]
      description: "High fallback usage may indicate specialist routing issues"
    - condition: "routing_accuracy < 85%"
      severity: "warning"
      notification: ["slack"]
      description: "Low routing accuracy needs investigation"
    - condition: "customer_satisfaction < 4.0"
      severity: "warning"
      notification: ["email"]
      
  # Business metrics tracking
  business_metrics:
    track_routing_patterns: true
    track_information_requests: true
    track_complaint_categories: true
    track_referral_success_rates: true
    track_fallback_scenarios: true

# Security Configuration
security:
  # General security settings (less sensitive than specialists)
  data_retention_days: 30      # Shorter retention for general inquiries
  encrypt_customer_info: true
  mask_sensitive_data: true
  log_routing_decisions: true
  
  # Access controls
  role_based_access:
    - role: "general_agent"
      permissions: ["basic_info_access", "routing", "ticket_creation"]
    - role: "general_supervisor"
      permissions: ["all_general_operations", "complaint_handling"]
  
  # Limited system access for security
  system_restrictions:
    no_payment_access: true
    no_emergency_systems: true
    limited_customer_data: true
    routing_only_capabilities: true

# Backup and Failover
failover:
  backup_agent: null           # No backup - this IS the backup
  health_check_interval: 30
  max_failures_before_alert: 5  # Higher threshold before alerts
  automatic_recovery: true
  recovery_check_interval: 60
  
  # Specialist failover configuration
  specialist_failover:
    handle_overflow: true       # Accept overflow from specialists
    emergency_bypass: false     # Never handle emergencies directly
    billing_bypass: false      # Never handle billing directly
    technical_bypass: false    # Never handle technical directly

# Integration Testing
testing:
  smoke_tests:
    - "company_info_lookup"
    - "agent_routing_decision"
    - "ticket_creation"
    - "availability_check"
  
  routing_tests:
    test_scenarios:
      - "general_information_request"
      - "specialist_routing_decision" 
      - "complaint_handling"
      - "fallback_scenario"
      - "overflow_handling"
    
    routing_accuracy_tests:
      emergency_routing: "must_route_to_roadside"
      billing_routing: "must_route_to_billing"
      technical_routing: "must_route_to_technical"
      general_handling: "handle_appropriately"
    
  load_tests:
    concurrent_sessions: 50    # Test higher load capacity
    test_duration_minutes: 30  # Longer duration test
    success_rate_threshold: 92  # Slightly lower threshold acceptable

# Learning and Improvement
continuous_improvement:
  routing_optimization:
    track_routing_decisions: true
    learn_from_corrections: true
    improve_keyword_matching: true
    optimize_confidence_thresholds: true
    
  knowledge_management:
    update_company_info_regularly: true
    track_information_gaps: true
    crowdsource_faq_updates: true
    validate_information_accuracy: true
    
  customer_experience:
    analyze_satisfaction_feedback: true
    identify_improvement_opportunities: true
    optimize_handoff_procedures: true
    reduce_customer_effort_score: true

# Fallback Configuration
fallback_behavior:
  when_specialists_unavailable:
    acknowledge_limitation: true
    offer_alternatives: ["callback", "ticket", "email"]
    provide_estimated_wait_times: true
    collect_contact_info: true
    
  when_unable_to_help:
    honest_about_limitations: true
    offer_human_escalation: true
    document_knowledge_gaps: true
    suggest_alternative_channels: true
    
  emergency_detection:
    escalate_immediately: true
    never_attempt_emergency_help: true
    provide_emergency_numbers: true
    document_emergency_attempts: true